// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opgaver_lek10.DAL;

#nullable disable

namespace Opgaver_lek10.Migrations
{
    [DbContext(typeof(ElevContext))]
    [Migration("20260310093231_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KlasseLære", b =>
                {
                    b.Property<int>("KlasserKlasseId")
                        .HasColumnType("int");

                    b.Property<int>("LærerLæreID")
                        .HasColumnType("int");

                    b.HasKey("KlasserKlasseId", "LærerLæreID");

                    b.HasIndex("LærerLæreID");

                    b.ToTable("KlasseLære");
                });

            modelBuilder.Entity("Opgaver_lek10.Model.Elev", b =>
                {
                    b.Property<int>("ElevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElevID"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("klasseId")
                        .HasColumnType("int");

                    b.HasKey("ElevID");

                    b.HasIndex("klasseId");

                    b.ToTable("Elever");

                    b.HasData(
                        new
                        {
                            ElevID = 1,
                            Adresse = "Solsikkevej 67",
                            CPR = "140189-1234",
                            Navn = "Vilje",
                            klasseId = 1
                        });
                });

            modelBuilder.Entity("Opgaver_lek10.Model.Klasse", b =>
                {
                    b.Property<int>("KlasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlasseId"));

                    b.Property<string>("KlasseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlasseId");

                    b.ToTable("Klasser");

                    b.HasData(
                        new
                        {
                            KlasseId = 1,
                            KlasseName = "1A"
                        });
                });

            modelBuilder.Entity("Opgaver_lek10.Model.Lære", b =>
                {
                    b.Property<int>("LæreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LæreID"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LæreID");

                    b.ToTable("Lærer");
                });

            modelBuilder.Entity("KlasseLære", b =>
                {
                    b.HasOne("Opgaver_lek10.Model.Klasse", null)
                        .WithMany()
                        .HasForeignKey("KlasserKlasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opgaver_lek10.Model.Lære", null)
                        .WithMany()
                        .HasForeignKey("LærerLæreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Opgaver_lek10.Model.Elev", b =>
                {
                    b.HasOne("Opgaver_lek10.Model.Klasse", "klasse")
                        .WithMany("Elever")
                        .HasForeignKey("klasseId");

                    b.Navigation("klasse");
                });

            modelBuilder.Entity("Opgaver_lek10.Model.Klasse", b =>
                {
                    b.Navigation("Elever");
                });
#pragma warning restore 612, 618
        }
    }
}
