// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using opg2.DAL;

#nullable disable

namespace opg2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260312103541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("opg2.Calculation", b =>
                {
                    b.Property<int>("CalculationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculationId"));

                    b.Property<string>("_operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("result")
                        .HasColumnType("int");

                    b.Property<int>("tal1")
                        .HasColumnType("int");

                    b.Property<int>("tal2")
                        .HasColumnType("int");

                    b.HasKey("CalculationId");

                    b.ToTable("calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
